apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stuckoverbug-server-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DevOps-Tim1-CDEF/Backend-Socket.git
    targetRevision: HEAD
    # path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: server

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
