apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stuckoverbug-server-app
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  # annotations:
  #   argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  project: default
  source:
    repoURL: https://github.com/DevOps-Tim1-CDEF/Backend-Socket.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: server

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      # - ServerSideApply=true
      # - Replace=true

    automated:
      selfHeal: true
      prune: true
# operation:
#   sync:
#     syncStrategy:
#       hook:
#         force: true
