apiVersion: apps/v1
kind: Deployment
metadata:
  name: stuckoverbug-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stuckoverbug-server
  template:
    metadata:
      labels:
        app: stuckoverbug-server
    spec:
      containers:
        - name: stuckoverbug-server
          image: r10f/stuckoverbug-server:main
          imagePullPolicy: Always
          ports:
            - containerPort: 2500
---
apiVersion: v1
kind: Service
metadata:
  name: stuckoverbug-server
spec:
  type: NodePort
  ports:
    - port: 2500 # Service port
      targetPort: 2500 # Container port
      nodePort: 30001
      protocol: TCP
  selector:
    app: stuckoverbug-server
