apiVersion: apps/v1
kind: Deployment
metadata:
  name: stuckoverbug-server
spec:
  selector:
    matchLabels:
      app: stuckoverbug-server
  template:
    metadata:
      labels:
        app: stuckoverbug-server
    spec:
      containers:
        - name: stuckoverbug-server
          image: r10f/stuckoverbug-server:main
          resources:
            requests:
              cpu: 10m
          imagePullPolicy: Always
          ports:
            - containerPort: 2500
---
apiVersion: v1
kind: Service
metadata:
  name: stuckoverbug-server
spec:
  type: NodePort
  ports:
    - port: 2500 # Service port
      targetPort: 2500 # Container port
      nodePort: 30001
      protocol: TCP
  selector:
    app: stuckoverbug-server
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stuckoverbug-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stuckoverbug-server
  minReplicas: 2
  maxReplicas: 10
  metrics: # Corrected indentation here
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
