version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports: 
      - "4000:2500"
    environment:
      PORT: 2500
      MONGODB_URI: mongodb+srv://adm_devops:ZGeC48LaIrCFBsD5@devops.mojcl.mongodb.net/dbDevOps?retryWrites=true&w=majority&appName=devops
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
