apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stuckoverbug-server-hpa
  namespace: server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stuckoverbug-server
  minReplicas: 2
  maxReplicas: 15
  metrics: # Corrected indentation here
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
